onlineshop-master/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

onlineshop-master/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls'))
]

onlineshop-master/coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name='coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),
]

onlineshop-master/order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

onlineshop-master/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

onlineshop-master/cart/models.py
from django.db import models

# Create your models here.

onlineshop-master/cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

onlineshop-master/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from coupon.forms import AddCouponForm
from .forms import AddProductForm
from .cart import Cart


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'], 'is_update':True})
    return render(request, 'cart/detail.html', {'cart':cart, 'add_coupon':add_coupon})

onlineshop-master/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img-thumbnail">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:product_add" product.id %}" method="post">
                        {{ item.quantity_form.quantity }}
                        {{ item.quantity_form.is_update }}
                        <input type="submit" class="btn btn-primary" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:product_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td >${{ cart.get_product_total }}</td>
            </tr>
            <tr>
                    <td>"{{ cart.coupon.code }}" coupon (${{ cart.coupon.amount }})</td>
                <td colspan="4"></td>
                <td >- ${{ cart.get_discount_total|floatformat:"2" }}</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
        </tr>
        </tbody>
    </table>
    <p>
        Add Coupon:
    </p>
    <form action='{% url "coupon:add" %}' method="post">
        {{ add_coupon }}
        <input type="submit" value="Add">
        {% csrf_token %}
    </form>


    <p class="text-right">
        <a href='{% url "shop:product_all" %}' class="btn btn-secondary">Continue shopping</a>
        <a href='{% url "orders:order_create" %}' class="btn btn-primary">Checkout</a>
    </p>
{% endblock %}